language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
branches:
  only:
  - master
matrix:
  allow_failures:
  - node_js: '0.11'
notifications:
  email: false
deploy:
  provider: npm
  email: aeneascorrupt@gmail.com
  api_key:
    secure: YE5ko05tjl9Kq2rP9CT13L+sXopzhpVBdZ3U/oXz82E4Gl8gB2Pc+kJHWPaUBwqSzs19nK2g+3OEj3Z4U+RVEFmaypR7LRU8CMOYLl9IG9kXRC3bR+wsazijhjcYpo+blox/L/t6zWFzhYYXboMS0tcpFNWwH3LRVV16xzl4BdI=
  on:
    branch: master
    repo: FenrirUnbound/flipit
